FROM php:apache


#
# User Actions
#

# RUN mkdir /var/www/html


#
# Install core 
#

# run apt-get update && apt-get install -y \
# unzip \
# curl 

#
# Add files
#

#
# Change defaults
#

# WORKDIR /var/www/html
# USER www-data
# CMD ["apache2-foreground"]

